[package]
name = "log_tailer"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8.6", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Navigator", "console", "Blob", "File", "Document", "Event", "Permissions", "PermissionStatus", "DomException", "ServiceWorkerContainer"] }
regex = "1"
once_cell = "1"
console_log = "1"
console_error_panic_hook = "0.1.7"
idb = "0.6.4"
serde = { version = "1", features = ["derive"] }
log = "0.4"
gloo-timers = { version = "0.3", features = ["futures"] }
futures = "0.3"

# Optional: nicer console logs in wasm
wasm-logger = "0.2"
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
csr = []
default = ["csr"]
